#Change the name to match your course name

#Example name: Deploy HTML Files to AppService - COURSENAME
name: Deploy HTML Files to AppService - CMST385
on:

  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@main

    - name: Deploy to Azure Web App - CMST385

      uses: azure/webapps-deploy@v1

      with:

      app-name: CMST385-UMGC-nalvarez17 - Web Deploy

      slot-name: production
        
      publish-profile: ${{ secrets.APPSERVICECMST385 }}
